services:
  tiendaservicios.api.autor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6104:80"

  tiendaservicios.api.libro:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6105:80"


  tiendaservicios.api.carritocompra:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Libros=http://tiendaservicios.api.libro
    ports:
      - "6106:80"


  tiendaservicios.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Autor=http://tiendaservicios.api.gateway
    depends_on: 
      - tiendaservicios.api.libro
    ports:
      - "6107:80"

